name: geoimage
description: A geo-wrapper around the image project (https://pub.dev/packages/image)
version: 0.2.0
homepage: https://github.com/moovida/geoimage

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  path:

  dart_jts:

  # Apache 2.0
  image: ^3.0.2
    # git:
    #   url: https://github.com/brendan-duncan/image.git
    #   ref: tiff_hdr_refactor


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.17.10
